name: incode-kanban
services:
  mongo:
    image: mongo:latest
    container_name: mongo-incode-kanban
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: incode-kanban
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/mongo
    command: ["--auth"]

volumes:
  mongodb_data:
